### ISSUE TITLE
[SET.2] cannot access setup page

### ISSUE THREAD

**Issue by mwigham** [polifonia-project/registry_app#40]
The setup page does not open automatically the first time the application is run, I get the Hello World page. If I click on 'Member Area', then I get a 404, when the browser tries to open [this link](https://github.com/login/oauth/authorize?client_id=09f1****************&scope=repo%20read:user). (Installing under Windows with Vagrant)

This issue is a blocker for me as I can't test most of the remaining functionality without access to the backend.

**Comment by marilenadaquino** [comment]
oops, I din't upload the correct config file. can you try again please?

**Comment by mwigham** [comment]
That's fixed it, great, thanks!

Perhaps handy to add to the README how you can stop vagrant and restart it
after a change in the repo

Op di 5 okt. 2021 om 13:18 schreef marilenadaquino ***@***.***

**Comment by hlostam** [comment]
You can run `vagrant reload` to do exactly this, I will include this in the new README.md file.
